### PR TITLE
chore(tests): upgrade cypress version

### PR DESCRIPTION
**Pull request by abirembaut**
- upgrade cypress to 4.12.1
- update cucumber preprocessor to 2.5.5
- filter the tests files to only run .feature file (to avoid issues when
git creates temp files)
- fix profiles list tests (type() inside a disable field now requires a
force option)

### CODE REVIEW

**Comment by DumitruCorini** [comment]
Um, there are other type() functions in other places, why do those work?

**Comment by DumitruCorini** [comment]
LGTM

**Comment by abirembaut** [comment]
@DumitruCorini I guess because we are not trying to type in a disabled field in other tests. Maybe this test is not relevant but this is not the point of this PR

**Comment by DumitruCorini** [comment]
Yeah, ok, that's why I deleted my comment

**Comment by DumitruCorini** [comment]
LGTM

**Pull request merged**
