### PR TITLE
fix(admin roles): Avoid disabling search when there is something in it

### PR DESCRIPTION
**Pull request by DumitruCorini**
covers [BR-593](https://bonitasoft.atlassian.net/browse/BR-593)

### CODE REVIEW

**Comment by VishalThapaliya** [comment]
I think the message "There are no users mapped to this role" should be changed to "No users to display". Except that everything looks good to me.

**Comment by abirembaut** [comment]
@VishalThapaliya @DumitruCorini I would even say: "No users with this role"
no ?

**Comment by DumitruCorini** [comment]
Group list we say: There are no users in this group
User list: No users to display
Profile list: No users to display
I think we should go with No users to display

**Comment by abirembaut** [comment]
@DumitruCorini I agree and we should do the same in the group list

**Comment by abirembaut** [comment]
I think french is missing for the localization.json of the group list. Other than that it is ready to merge

**Pull request merged**
